/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PokeSearch {
        "focusInput": () => Promise<void>;
    }
}
declare global {
    interface HTMLPokeSearchElement extends Components.PokeSearch, HTMLStencilElement {
    }
    var HTMLPokeSearchElement: {
        prototype: HTMLPokeSearchElement;
        new (): HTMLPokeSearchElement;
    };
    interface HTMLElementTagNameMap {
        "poke-search": HTMLPokeSearchElement;
    }
}
declare namespace LocalJSX {
    interface PokeSearch {
    }
    interface IntrinsicElements {
        "poke-search": PokeSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "poke-search": LocalJSX.PokeSearch & JSXBase.HTMLAttributes<HTMLPokeSearchElement>;
        }
    }
}
