/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PokeList {
    }
    interface PokeSearch {
        "focusInput": () => Promise<void>;
        "pokemonName": string;
    }
}
declare global {
    interface HTMLPokeListElement extends Components.PokeList, HTMLStencilElement {
    }
    var HTMLPokeListElement: {
        prototype: HTMLPokeListElement;
        new (): HTMLPokeListElement;
    };
    interface HTMLPokeSearchElement extends Components.PokeSearch, HTMLStencilElement {
    }
    var HTMLPokeSearchElement: {
        prototype: HTMLPokeSearchElement;
        new (): HTMLPokeSearchElement;
    };
    interface HTMLElementTagNameMap {
        "poke-list": HTMLPokeListElement;
        "poke-search": HTMLPokeSearchElement;
    }
}
declare namespace LocalJSX {
    interface PokeList {
        "onSelectedPokemonName"?: (event: CustomEvent<string>) => void;
    }
    interface PokeSearch {
        "pokemonName"?: string;
    }
    interface IntrinsicElements {
        "poke-list": PokeList;
        "poke-search": PokeSearch;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "poke-list": LocalJSX.PokeList & JSXBase.HTMLAttributes<HTMLPokeListElement>;
            "poke-search": LocalJSX.PokeSearch & JSXBase.HTMLAttributes<HTMLPokeSearchElement>;
        }
    }
}
